<a href="https://colab.research.google.com/github/Deekshith1064/B21_1414/blob/main/Lab_03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
test_scores = np.random.randint(50, 101, size=(4, 4))
print(test_scores)

[[64 62 70 90]
 [67 55 64 96]
 [83 65 95 58]
 [54 67 61 73]]


In [3]:
column_means = np.mean(test_scores, axis=0)
row_means = np.mean(test_scores, axis=1)

print("Column-wise means:", column_means)
print("Row-wise means:", row_means)

Column-wise means: [67.   62.25 72.5  79.25]
Row-wise means: [71.5  70.5  75.25 63.75]


In [4]:
std_dev = np.std(test_scores)
variance = np.var(test_scores)

print("Standard Deviation:", std_dev)
print("Variance:", variance)

Standard Deviation: 13.141061600951424
Variance: 172.6875


In [5]:
min_value = np.min(test_scores)
max_value = np.max(test_scores)
min_index = np.argmin(test_scores)
max_index = np.argmax(test_scores)

print("Minimum value:", min_value)
print("Maximum value:", max_value)
print("Index of minimum value:", min_index)
print("Index of maximum value:", max_index)

Minimum value: 54
Maximum value: 96
Index of minimum value: 12
Index of maximum value: 7


In [6]:
print("Statistical Analysis Summary:")
print(f"Row-wise means: {row_means}")
print(f"Column-wise means: {column_means}")
print(f"Overall Standard Deviation: {std_dev}")
print(f"Overall Variance: {variance}")
print(f"Global Minimum Value: {min_value} (Index: {min_index})")
print(f"Global Maximum Value: {max_value} (Index: {max_index})")

Statistical Analysis Summary:
Row-wise means: [71.5  70.5  75.25 63.75]
Column-wise means: [67.   62.25 72.5  79.25]
Overall Standard Deviation: 13.141061600951424
Overall Variance: 172.6875
Global Minimum Value: 54 (Index: 12)
Global Maximum Value: 96 (Index: 7)


In [7]:
rgb_image = np.random.randint(0, 256, size=(3, 3, 3))
print(rgb_image)

[[[ 20 169  65]
  [  2 102 186]
  [ 73 172  76]]

 [[ 52 136 107]
  [ 40 166 126]
  [224  86  91]]

 [[233 138 169]
  [  9 101 198]
  [129 173 163]]]


In [9]:
red_channel = rgb_image[:, :, 0]
green_channel = rgb_image[:, :, 1]
blue_channel = rgb_image[:, :, 2]
print("Red Channel:\n", red_channel)
print("Green Channel:\n", green_channel)
print("Blue Channel:\n", blue_channel)

Red Channel:
 [[ 20   2  73]
 [ 52  40 224]
 [233   9 129]]
Green Channel:
 [[169 102 172]
 [136 166  86]
 [138 101 173]]
Blue Channel:
 [[ 65 186  76]
 [107 126  91]
 [169 198 163]]


In [10]:
red_mean = np.mean(red_channel)
green_mean = np.mean(green_channel)
blue_mean = np.mean(blue_channel)
print(f"Average pixel intensity for Red channel: {red_mean}")
print(f"Average pixel intensity for Green channel: {green_mean}")
print(f"Average pixel intensity for Blue channel: {blue_mean}")

Average pixel intensity for Red channel: 86.88888888888889
Average pixel intensity for Green channel: 138.11111111111111
Average pixel intensity for Blue channel: 131.22222222222223


In [11]:
brightness_increase = 50
brightened_image = np.clip(rgb_image + brightness_increase, 0, 255)
print("Brightened Image (clipped at 255):\n", brightened_image)

Brightened Image (clipped at 255):
 [[[ 70 219 115]
  [ 52 152 236]
  [123 222 126]]

 [[102 186 157]
  [ 90 216 176]
  [255 136 141]]

 [[255 188 219]
  [ 59 151 248]
  [179 223 213]]]


In [12]:
print("Statistical Analysis Summary:")
print("Red Channel:\n", red_channel)
print("Green Channel:\n", green_channel)
print("Blue Channel:\n", blue_channel)
print(f"\nAverage pixel intensity for Red channel: {red_mean}")
print(f"Average pixel intensity for Green channel: {green_mean}")
print(f"Average pixel intensity for Blue channel: {blue_mean}")
print("\nBrightened Image (clipped at 255):\n", brightened_image)

Statistical Analysis Summary:
Red Channel:
 [[ 20   2  73]
 [ 52  40 224]
 [233   9 129]]
Green Channel:
 [[169 102 172]
 [136 166  86]
 [138 101 173]]
Blue Channel:
 [[ 65 186  76]
 [107 126  91]
 [169 198 163]]

Average pixel intensity for Red channel: 86.88888888888889
Average pixel intensity for Green channel: 138.11111111111111
Average pixel intensity for Blue channel: 131.22222222222223

Brightened Image (clipped at 255):
 [[[ 70 219 115]
  [ 52 152 236]
  [123 222 126]]

 [[102 186 157]
  [ 90 216 176]
  [255 136 141]]

 [[255 188 219]
  [ 59 151 248]
  [179 223 213]]]
